version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_URL_API: http://localhost:8000/api # On pointe vers le service backend
    ports:
      - "80:80" # Expose sur le port 80 en prod
    networks:
      - npm-network
    restart: unless-stopped

networks:
  npm-network:
    external: true
